FROM node:13.11

RUN mkdir /opt/src
WORKDIR /opt/src

RUN npm install --global http-server

RUN git clone --depth=1 \
    https://github.com/radiantearth/stac-browser \
    --branch v2.0.0

WORKDIR /opt/src/stac-browser

RUN npm install

WORKDIR /opt/src/stac-browser

CMD ["npm", "start"]

